apiVersion: v1
kind: Pod
metadata:
  name: pod-using-secret
spec:
  containers:
  - name: pod-using-secret
    image: busybox
    command: ["/bin/sleep","2592000"]
    volumeMounts:
    - mountPath: "/mnt/lzfs"
      name: lzfs-test
  volumes:
  - name: lzfs-test
    flexVolume:
      driver: fq/lizardfs
      options:
        host: "mfsmaster"
        port: "9421"
        mfssubfolder: "/base/subfolder"
      secretRef:
        name: pod-lzfs-secret
